version: '3.9'
services:
  bro:
    image: ghcr.io/lameaux/bro:latest
    volumes:
      - ./bro-scenarios:/scenarios
  brod:
    image: ghcr.io/lameaux/bro:latest
    entrypoint: ["/brod"]
    command: ["--debug"]
    restart: "unless-stopped"
  mox:
    image: ghcr.io/lameaux/mox:latest
    command: ["--debug"]
    ports:
      - "8080:8080"
      - "8181:8181"
    volumes:
      - ./mox-config:/config
    restart: "unless-stopped"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: "unless-stopped"
    depends_on:
      - mox
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: "unless-stopped"
    volumes:
      - ./prometheus-config:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: "unless-stopped"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana-config:/etc/grafana/provisioning/datasources
volumes:
  prom_data: