version: '3.9'
services:
  mox:
    image: ghcr.io/lameaux/mox:latest
    command: ["--debug"]    
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9090:9090"      
    environment:
      - ENV_VAR_NAME=value
    volumes:
      - ./mox-mappings:/mappings
    restart: "unless-stopped"
  bro:
    image: ghcr.io/lameaux/bro:latest
    ports:
      - "9090:9090"
    volumes:
      - ./bro-scenarios:/scenarios
