version: '3.9'
services:
  bro:
    image: ghcr.io/lameaux/bro:latest
    volumes:
      - ./bro-scenarios:/scenarios
  mox:
    image: ghcr.io/lameaux/mox:latest
    command: ["--debug"]
    volumes:
      - ./mox-config:/config
    restart: "unless-stopped"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: "unless-stopped"
    depends_on:
      - mox