apiVersion: apps/v1
kind: Deployment
metadata:
  name: mox
  labels:
    app: mox
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: mox
  template:
    metadata:
      labels:
        app: mox
    spec:
      containers:
        - name: mox
          image: ghcr.io/lameaux/mox:latest
          resources: {{ toYaml .Values.resources | nindent 12 }}
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          args:
            - "--debug={{ .Values.flags.debug }}"
            - "--accessLog={{ .Values.flags.accessLog }}"
            - "--configPath=./config"
            - "--port={{.Values.ports.http }}"
            - "--adminPort={{.Values.ports.admin }}"
            - "--pprofPort={{.Values.ports.pprof }}"
          ports:
            - name: http
              containerPort: {{ .Values.ports.http }}
            - name: admin
              containerPort: {{ .Values.ports.admin }}
            - name: pprof
              containerPort: {{ .Values.ports.pprof }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: mox-files
              mountPath: /config/files
            - name: mox-mappings
              mountPath: /config/mappings
            - name: mox-templates
              mountPath: /config/templates
      volumes:
        - name: mox-files
          configMap:
            name: mox-files
        - name: mox-mappings
          configMap:
            name: mox-mappings
        - name: mox-templates
          configMap:
            name: mox-templates