apiVersion: v1
kind: Service
metadata:
  name: brod
  labels:
    app: brod
spec:
  type: {{ .Values.service.type }}
  selector:
    app: brod
  ports:
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: {{ .Values.ports.grpc }}
    - name: rest
      port: {{ .Values.ports.rest }}
      targetPort: {{ .Values.ports.rest }}