apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ now | date "20060102150405" }}
spec:
  parallelism: {{ .Values.parallelism }}
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: bro
          image: ghcr.io/lameaux/bro:latest
          resources: {{ toYaml .Values.resources | nindent 12 }}
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          args:
            - "--debug={{ .Values.flags.debug }}"
            - "--brodAddr={{ .Values.flags.brodAddr }}"
            - "/scenarios/scenario.yaml"
          volumeMounts:
            - name: bro-scenarios
              mountPath: /scenarios
      volumes:
        - name: bro-scenarios
          configMap:
            name: bro-scenarios-{{ .Release.Name }}
      restartPolicy: Never