---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-stdlib
  labels:
    app: golang-stdlib
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: golang-stdlib
  template:
    metadata:
      labels:
        app: golang-stdlib
    spec:
      containers:
        - name: golang-stdlib
          image: ghcr.io/lameaux/nft/apps/httpserver/golang/stdlib:latest
          resources: {{ toYaml .Values.resources | nindent 12 }}
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          args:
            - "--port={{.Values.ports.golang.stdlib }}"
          ports:
            - name: http
              containerPort: {{.Values.ports.golang.stdlib }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
