---
apiVersion: v1
kind: Service
metadata:
  name: golang-stdlib
  labels:
    app: golang-stdlib
spec:
  type: {{ .Values.service.type }}
  selector:
    app: golang-stdlib
  ports:
    - name: http
      port: {{ .Values.ports.golang.stdlib }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: golang-fasthttp
  labels:
    app: golang-fasthttp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: golang-fasthttp
  ports:
    - name: http
      port: {{ .Values.ports.golang.fasthttp }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: golang-lowlevel
  labels:
    app: golang-lowlevel
spec:
  type: {{ .Values.service.type }}
  selector:
    app: golang-lowlevel
  ports:
    - name: http
      port: {{ .Values.ports.golang.lowlevel }}
      targetPort: http