apiVersion: v1
kind: Service
metadata:
  name: golang-stdlib
  labels:
    app: golang-stdlib
spec:
  type: {{ .Values.service.type }}
  selector:
    app: golang-stdlib
  ports:
    - name: http
      port: {{ .Values.ports.golang.stdlib }}
      targetPort: http
