replicas: 1
resources:
  requests:
    memory: "480Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "250m"
ports:
  golang:
    stdlib: 8081
    fasthttp: 8082
    lowlevel: 8083
  java:
    netty: 8091
    quarkus: 8092
  rust:
    axum: 8101
service:
  type: LoadBalancer # ClusterIP